import Course from "../models/Course.js";
import Lesson from "../models/Lesson.js";
import User from "../models/User.js";
import { generateCourseWithGemini } from "../services/ai/gemini.service.js";
import { clearUserCache, clearPublicCache } from "../utils/cacheInvalidator.js";

/* =====================================================
   POST /api/courses/generate
===================================================== */
export async function generateCourseController(req, res) {
  try {
    const { topic, level, language = "English", goal, timeAvailable } = req.body;

    // 🔐 Auth0 user id
    const userId = req.auth.sub;
    
    // Fetch user memory
    const user = await User.findOne({ auth0Id: userId });

    const content = await generateCourseWithGemini(topic, level, language, goal, timeAvailable, user);

    const course = await Course.create({
      topic,
      level,
      language,
      goal,
      timeAvailable,
      content,
      userId, // ✅ saved
    });

    // Invalidate Redis caches
    await clearUserCache(userId);
    await clearPublicCache();

    res.status(201).json({ success: true, data: course });
  } catch (e) {
    console.error(e);
    res.status(500).json({ success: false, message: "Course generation failed" });
  }
}

/* =====================================================
   GET /api/courses/my
   (ONLY logged-in user's courses)
===================================================== */
export async function getMyCourses(req, res) {
  try {
    const userId = req.auth.sub;

    const courses = await Course.find({ userId }).sort({ createdAt: -1 });

    return res.json({
      success: true,
      data: courses,
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to fetch user courses",
    });
  }
}

/* =====================================================
   GET /api/courses/public
   (All public courses generated by community)
===================================================== */
export const getPublicCourses = async (req, res) => {
  console.log("[API] /api/courses/public hit");
  const startTime = Date.now();
  try {
    const courses = await Course.find({ isPublic: true })
      .select("topic level language _id")
      .limit(20)
      .lean();
      
    console.log(`[API] /api/courses/public DB query took ${Date.now() - startTime}ms`);
    return res.json({ success: true, data: courses });
  } catch (error) {
    console.error(`[API] /api/courses/public error:`, error);
    return res.status(500).json({ success: false, message: "Failed to fetch public courses" });
  }
};

/* =====================================================
   GET /api/courses/:id
===================================================== */
export async function getCourseById(req, res) {
  try {
    const course = await Course.findById(req.params.id);

    if (!course) {
      return res.status(404).json({
        success: false,
        message: "Course not found",
      });
    }

    return res.json({
      success: true,
      data: course,
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to fetch course",
    });
  }
}

/* =====================================================
   GET /api/courses/:id/full
===================================================== */
export async function getFullCourseController(req, res) {
  try {
    const { id } = req.params;

    const course = await Course.findById(id).lean();
    if (!course) {
      return res.status(404).json({
        success: false,
        message: "Course not found",
      });
    }

    // 🔥 Fetch cached lessons
    const lessons = await Lesson.find({ courseId: id }).lean();

    const lessonMap = {};
    lessons.forEach((lesson) => {
      const key = `${lesson.moduleIndex}-${lesson.lessonIndex}`;
      lessonMap[key] = lesson.content;
    });

    course.content.modules.forEach((module) => {
      module.lessons = module.lessons.map((lesson) => {
        const key = `${module.moduleIndex}-${lesson.lessonIndex}`;
        return {
          ...lesson,
          fullContent: lessonMap[key] || null,
        };
      });
    });

    return res.json({
      success: true,
      data: course,
    });

  } catch (error) {
    console.error("❌ Full course fetch error:", error);
    return res.status(500).json({
      success: false,
      message: "Failed to fetch full course",
    });
  }
}

/* =====================================================
   DELETE /api/courses/:id
===================================================== */
export async function deleteCourseController(req, res) {
  try {
    const { id } = req.params;
    const userId = req.auth.sub;

    const course = await Course.findById(id);

    if (!course) {
      return res.status(404).json({
        success: false,
        message: "Course not found",
      });
    }

    // Check if the user is the owner of the course
    if (course.userId !== userId) {
      return res.status(403).json({
        success: false,
        message: "You are not authorized to delete this course",
      });
    }

    await Course.findByIdAndDelete(id);
    
    // Delete associated lessons
    await Lesson.deleteMany({ courseId: id });

    // Invalidate Redis caches
    await clearUserCache(userId);
    await clearPublicCache();

    return res.json({
      success: true,
      message: "Course deleted successfully",
    });
  } catch (error) {
    console.error("❌ Course deletion error:", error);
    return res.status(500).json({
      success: false,
      message: "Failed to delete course",
    });
  }
}