import User from "../models/User.js";
import Course from "../models/Course.js";
import Progress from "../models/Progress.js";
import { clearUserCache } from "../utils/cacheInvalidator.js";

/* =====================================================
   POST /api/users/sync
   Called by frontend on login to ensure user exists
===================================================== */
export async function syncUser(req, res) {
  try {
    const { email, name, picture } = req.body;
    const auth0Id = req.auth.sub; // From auth0 middleware

    let existingUser = await User.findOne({ auth0Id });
    let streak = 1;

    if (existingUser && existingUser.lastActive) {
      const now = new Date();
      const lastActive = new Date(existingUser.lastActive);
      
      const nowDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
      const lastActiveDate = new Date(lastActive.getFullYear(), lastActive.getMonth(), lastActive.getDate());
      
      const diffTime = nowDate.getTime() - lastActiveDate.getTime();
      const diffDays = diffTime / (1000 * 60 * 60 * 24); 
      
      if (diffDays === 1) {
        streak = (existingUser.streak || 0) + 1;
      } else if (diffDays === 0) {
        streak = existingUser.streak || 1;
      } else {
        streak = 1;
      }
    }

    // Upsert user
    const user = await User.findOneAndUpdate(
      { auth0Id },
      { email, name, picture, lastActive: new Date(), streak },
      { new: true, upsert: true }
    );

    return res.json({ success: true, data: user });
  } catch (error) {
    console.error("Sync user error:", error);
    return res.status(500).json({ success: false, message: "Failed to sync user" });
  }
}

/* =====================================================
   GET /api/users/dashboard
   Returns user stats and their generated courses
===================================================== */
export async function getDashboard(req, res) {
  try {
    const auth0Id = req.auth.sub;

    // 1. Get courses generated by user
    const userCourses = await Course.find({ userId: auth0Id }).lean();

    // 2. Get progress records to find enrolled courses
    const progressRecords = await Progress.find({ userId: auth0Id }).lean();
    const progressCourseIds = progressRecords.map(p => p.courseId);

    // 3. Get enrolled courses
    const enrolledCourses = await Course.find({ _id: { $in: progressCourseIds } }).lean();

    // 4. Merge uniquely and sort by latest
    const allCoursesMap = new Map();
    userCourses.forEach(c => allCoursesMap.set(c._id.toString(), c));
    enrolledCourses.forEach(c => allCoursesMap.set(c._id.toString(), c));
    const courses = Array.from(allCoursesMap.values()).sort((a, b) => b.createdAt - a.createdAt);

    // 2. Map progress by courseId
    const progressMap = {};
    progressRecords.forEach(p => {
      progressMap[p.courseId.toString()] = p.completedLessons;
    });

    // 3. Calculate total lessons per course to find % complete
    let totalCoursesCompleted = 0;
    let totalCoursesInProgress = 0;

    const enrichedCourses = courses.map(course => {
      let totalLessons = 0;
      course.content.modules.forEach(m => {
        totalLessons += m.lessons.length;
      });

      const completed = progressMap[course._id.toString()] || [];
      const isCompleted = totalLessons > 0 && completed.length === totalLessons;
      const isInProgress = completed.length > 0 && !isCompleted;

      if (isCompleted) totalCoursesCompleted++;
      if (isInProgress) totalCoursesInProgress++;
      
      return {
        _id: course._id,
        topic: course.topic,
        level: course.level,
        createdAt: course.createdAt,
        totalLessons,
        completedLessonsCount: completed.length,
        isCompleted
      };
    });

    const user = await User.findOne({ auth0Id }).lean();
    
    return res.json({
      success: true,
      data: {
        stats: {
          totalCourses: courses.length,
          totalCoursesCompleted,
          totalCoursesInProgress,
          xp: user?.xp || 0,
          streak: user?.streak || 0,
          strongTopics: user?.strongTopics || [],
          weakTopics: user?.weakTopics || [],
          quizHistory: user?.quizHistory || [],
          learningTime: user?.learningTime || 0
        },
        recentCourses: enrichedCourses
      }
    });

  } catch (error) {
    console.error("Dashboard fetch error:", error);
    return res.status(500).json({ success: false, message: "Failed to fetch dashboard data" });
  }
}

/* =====================================================
   POST /api/users/progress
   Mark a lesson as complete or incomplete
===================================================== */
export async function markProgress(req, res) {
  try {
    const auth0Id = req.auth.sub;
    const { courseId, lessonId, isCompleted } = req.body; // lessonId is like "1-2" (module-lesson)

    let progress = await Progress.findOne({ userId: auth0Id, courseId });

    if (!progress) {
      progress = new Progress({ userId: auth0Id, courseId, completedLessons: [] });
    }

    if (isCompleted) {
      if (!progress.completedLessons.includes(lessonId)) {
        progress.completedLessons.push(lessonId);
        
        // Award 10 XP
        await User.findOneAndUpdate(
          { auth0Id },
          { $inc: { xp: 10 } }
        );
      }
    } else {
      progress.completedLessons = progress.completedLessons.filter(id => id !== lessonId);
    }

    await progress.save();

    await clearUserCache(auth0Id);

    return res.json({ success: true, data: progress.completedLessons });
  } catch (error) {
    console.error("Mark progress error:", error);
    return res.status(500).json({ success: false, message: "Failed to update progress" });
  }
}

/* =====================================================
   GET /api/users/progress/:courseId
   Get completed lessons for a specific course
===================================================== */
export async function getCourseProgress(req, res) {
  try {
    const auth0Id = req.auth.sub;
    const { courseId } = req.params;

    const progress = await Progress.findOne({ userId: auth0Id, courseId });

    return res.json({ success: true, data: progress ? progress.completedLessons : [] });
  } catch (error) {
    console.error("Get progress error:", error);
    return res.status(500).json({ success: false, message: "Failed to fetch progress" });
  }
}

/* =====================================================
   POST /api/users/xp
   Award XP for specific actions (like Quiz perfect score)
===================================================== */
export async function addXp(req, res) {
  try {
    const auth0Id = req.auth.sub;
    const { amount } = req.body;

    if (!amount || typeof amount !== 'number') {
      return res.status(400).json({ success: false, message: "Valid XP amount is required" });
    }

    const user = await User.findOneAndUpdate(
      { auth0Id },
      { $inc: { xp: amount } },
      { new: true }
    );

    await clearUserCache(auth0Id);

    return res.json({ success: true, xp: user.xp });
  } catch (error) {
    console.error("Add XP error:", error);
    return res.status(500).json({ success: false, message: "Failed to add XP" });
  }
}
